### ISSUE TITLE
Please upload line-sdk.aar to the Maven

### ISSUE THREAD

**Issue by bhbac-nhnent** [line/line-platform-feedback#100]
Hi.
I use line-sdk.aar to the project and develop it.

Currently I am using various SDKs, but since all SDKs can be downloaded from Maven, it is now possible to build projects just by setting Gradle.
However, line-sdk must specify a directly downloaded aar.
Line-sdk is the only SDK that does not offer SDK release to Maven.

For iOS, it supports CocoaPods setting. But I can not understand that it does not support Maven which is more public than CocoaPods.
The fact that the Android library does not support Maven strongly gives the impression that it is outdated now.
I am longing for the day when Maven will be able to download line-sdk.

Thanks.

**Comment by tokuhirom** [comment]
@GuitarSucks any plans?

**Comment by GuitarSucks** [comment]
I think we tried in the past before. For some reason we haven't finished the process yet.
I will check about it.

**Comment by mrmaakun** [comment]
We plan to upload the Android SDK to Maven from its next major release. This should happen in the next couple of months.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
