### ISSUE TITLE
Fix of location type message specification on Messaging API reference

### ISSUE THREAD

**Issue by ryz310** [line/line-platform-feedback#109]
On the [Messaging API references](
https://developers.line.me/ja/reference/messaging-api/#anchor-8b98a74f286c6de830e47fb623e1c87ffe2897a3), the location type message responses are as follows.

```json
{
  "replyToken": "nHuyWiB7yP5Zw52FIkcQobQuGDXCTA",
  "type": "message",
  "timestamp": 1462629479859,
  "source": {
    "type": "user",
    "userId": "U4af4980629..."
  },
  "message": {
    "id": "325708",
    "type": "location",
    "title": "my location",
    "address": "〒150-0002 東京都渋谷区渋谷２丁目２１−１",
    "latitude": 35.65910807942215,
    "longitude": 139.70372892916203
  }
}
```

However, sometimes has case of that the response does not include `title` property.
I'd like you to write that specification to the API reference.

**Comment by kazuki-ma** [comment]
@ryz310 Thank you for your feedback.
I confirmed the issue reported by you.
We'll update docs or SPEC (field suppressed or send as undefined?) soon.

Thank you.

Memo (Example)
---
```javascript
{
    "events": [
        {
            "type": "message",
            "replyToken": "c54f059078...",
            "source": {
                "userId": "Ue87f27...",
                "type": "user"
            },
            "timestamp": 1532163644267,
            "message": {
                "type": "location",
                "id": "8297547118571",
                "address": "日本、〒160-0022 東京都新宿区新宿３丁目 国道20号線",
                "latitude": 35.689512,
                "longitude": 139.70175
            }
        }
    ]
}
```

![screenshot_20180721-180630](https://user-images.githubusercontent.com/1370068/43034121-32afd0f6-8d11-11e8-8f1c-4eb694763d7d.png)

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
