### ISSUE TITLE
[Enhancment] Messaging API - GET messages of user endpoint

### ISSUE THREAD

**Issue by awharkrider** [line/line-platform-feedback#115]
It would be nice to have an API call that could get the messages of a LINE user that has exchanged messages with the LINE bot/channel. 

In the [Messaging API](https://developers.line.me/en/reference/messaging-api/#send-push-message) it would be useful to get an array/list of messages received by the LINE user by their userID. 

## Example use case:
For example I am testing the implementation of LINE bot with my companies application. Using a webhook event, I can send a message to my application using automation and then reply to that message from my application. The BOT correctly routes my applications message back to the LINE user, but I am unable to confirm the user receives this message using the API. If a GET users Messages endpoint existed then I could get that users messages they have received from the BOT and confirm that my applications message reached them.

**Possible endpoint?** 
GET https://api.line.me/v2/bot/message/{userID}
Request header: 
```
{
   "Authorization": "Bearer {channelAccessToken}" 
}
```

Possible response: 
List of messages received or a conversation history? 

If there is a way of getting the conversation history or users messages received that I missed, then please post on this issue or message me.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
