### ISSUE TITLE
When I tap an input item with liff, the keyboard rises up and some items hide

### ISSUE THREAD

**Issue by yasuo1watanabe** [line/line-platform-feedback#119]
When the keyboard is displayed by tapping the input item with liff like the image pasted below, the screen display will be pushed up to the top.

Is there a way to fix the screen display even when the keyboard is displayed?

 - ## Initial display
<div>
<img src="https://user-images.githubusercontent.com/37926263/48473955-e146de80-e83c-11e8-919e-297cd9252b67.png" width="400px">
</div>
<br>

 - ### Display after input item tap
<div>
<img src="https://user-images.githubusercontent.com/37926263/48473961-e441cf00-e83c-11e8-9d8a-b24721a73fe3.png" width="400px">
</div>

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
