### ISSUE TITLE
Is it possible to set the default directory of html input file type to gallery?

### ISSUE THREAD

**Issue by ken93939** [line/line-platform-feedback#120]
As we are developing a line liff application, we found that the behaviour in liff is different from android browser. While html standard, as far as I know, restricts the developer from choosing the default directory for html input file type element due to security concern, normal android browser would default the directory to gallery. However, in liff, it seems it is directed to Recent folder or Download folder, is there any way to set the default directory to gallery instead for better experience or can it be a feature update in the future? Thanks.
![android](https://user-images.githubusercontent.com/7888211/48684929-f336d180-ebee-11e8-82f0-e08e0d88976b.jpeg)
![dl](https://user-images.githubusercontent.com/7888211/48685026-4f015a80-ebef-11e8-8372-c97781c4ddb8.png)

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
