### ISSUE TITLE
programmable approach to generate qrcode using Messaging API

### ISSUE THREAD

**Issue by chentsulin** [line/line-platform-feedback#124]
In this official doc - [Sharing your bot with users](https://developers.line.biz/en/docs/messaging-api/sharing-bot/), it demonstrates how to get your LINE ID or your QR code from LINE Developers console or LINE@ Manager.

Is there any way to get my bot's LINE ID or generator QR code using Messaging API?

For example, Messenger can generate Messenger code using API:
https://developers.facebook.com/docs/messenger-platform/discovery/messenger-codes/

**Comment by synk** [comment]
At this time there are no API to programmatically get a code. Would you share your usecase for such API?

**Comment by chentsulin** [comment]
Hi @synk, we try to build a platform that helps people build LINE bots, so we want to show the QR Code on our platform as easy access to the bot. Users always spend a lot of time finding a link to get into the conversation to their bot, so if we can show the QR Code, it helps a lot.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
