### ISSUE TITLE
[Feature Request] Messaging API - Group Name 

### ISSUE THREAD

**Issue by BlackMix** [line/line-platform-feedback#126]
I think need add it on API..
We can get id but not the group name.. memorize ids is bad, there are many characters.. something else would be to add groupUpdate event to know if the type is image or name, so we can get a new image of the group or new  group name.

In the case I would only have to add the variables in the API to work this idea, but from what I saw here in github many things that the devs asks for takes time to happen, there are simple things for more than a year waiting... we will improve for everyone if felt that the Line is the best.

Line bots have a lot of limitation but releasing know the name of groups by id, and adding events to know when renaming or changing image will get better, so many devs people would be happy :)

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
