### ISSUE TITLE
Chat notes and albums

### ISSUE THREAD

**Issue by sura1997** [line/line-platform-feedback#15]
Do you have a plan to have a permission model that would allow bots to access Notes and Albums through Messaging API? Please consider the following suggestion:

There can be 5 permissions:
- write a note 
- create a new album
- add a photo to an album
- delete a note that it creates
- delete a photo that it adds

Each time the bot would like to do each of the above operations, a pop up can show up on the chat to ask for a permission for that specific operation. Any human can approve or disapprove the operation. 

Additionally there are permissions to allow the bot to do until the permissions are taken away by a human in the chat or the bot leaves the group. The permission are automatically given when a note or a photo is added by the bot. The auto permissions are:
- Read notes and comments, add comments, or edit notes (all these operations are allowed only for the notes that it creates)
- View photos (only for the photos that it adds)

Any human users in the chat can edit or delete notes/photos created by the bot without asking for a permission from anyone. 

I think opening up the notes and albums with proper permission model will allow bots to perform some more useful functions to the users while having the right balance on protecting privacy and properties of the users. 

What do you think?

**Comment by sura1997** [comment]
Just to clarify, bots should never have any access to any notes, comments and photos that it does not create to protect the privacy.

**Comment by GuitarSucks** [comment]
@sura1997 
Thank you for your comment.
We will consider such permissions but at this point we have no roadmap. And yes we need to consider user's privacy.

**Comment by dvcrn** [comment]
It's been roughly a year. Is accessing chat / group notes being considered currently?

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
