### ISSUE TITLE
LINE Bots collection

### ISSUE THREAD

**Issue by kakajansh** [line/line-platform-feedback#19]
Would be useful creating collection of LINE Bots created by developers. For implementations, usage and inspiration. 

We developed music bot "datmusic". For playing and downloading musics directly from LINE.
https://line.me/ti/p/@rdf0868k

![94507](https://user-images.githubusercontent.com/7093483/28494288-14a83f4a-6f43-11e7-97a1-d010d10b279f.jpg)

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
