### ISSUE TITLE
Account Linking

### ISSUE THREAD

**Issue by JTimings** [line/line-platform-feedback#30]
We have an existing database of customers (with accounts created NOT using LINE Login) and want to authenticate them from within our bot so we can use their account data, i.e addresses, payment info etc. to provide a more relevant/streamlined experience - is this possible?

I'm guessing something similar to this in FB Messenger => https://developers.facebook.com/docs/messenger-platform/identity/account-linking/

**Comment by kumai** [comment]
Hi, 

For the moment we're not providing such feature equivalent to the Facebook's Account Linking. You could link your bot's follower to your business customer by sending an invitation to your own authentication in a chat.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
