### ISSUE TITLE
How to save event.message.text as variable with a certain time period

### ISSUE THREAD

**Issue by RiskyID** [line/line-platform-feedback#31]
sorry my english is not good
I'm new in bot development

how to save the text we send into several variables, with a certain time period

**example**
I send the command "register"
bot replied "what is your first name?"
then I send the text "denis"
bot replied "what's your last name?"
I replied "tomson"
bot replied "your name is denis tomson"

**problem**
when I send "register" command or other command.
text commands that are stored in the variable.
so I asked how to use the command with a certain period of time

sorry this is not a problem about line bot SDK, but I do not know where to ask again because some forums do not discuss about line bot.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
