### ISSUE TITLE
Bot With Web Site 

### ISSUE THREAD

**Issue by mrsic** [line/line-platform-feedback#33]
Hi People, Sorry for my bad english

Im willy new in bot codin and i have lost alot time to setup all that works with my website.
I esplain my Problem

I have create a group on Line for Game that we play with 220 person
Then sombody enter and kick all users from group so sombody tell me to make a bot that protect the group. 
Creating bot and testing that in hard way why api php exaple code are not match and alot missing in developer console

I do already almost all about reply message with keywords from my website and that all work fine 
1. Ist the way from protecting users from kicking other users??? Or that sombody kick all users??

2. Ist possible create invite link from Group ID
3. Ist possible create link to a user from User ID

So i can save users in my db and connect them to  there profile on my website and i can use line bot for get people info direct from my website and thats willy help

If any solution to help me please answer here please

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
