### ISSUE TITLE
How to change the monthly plan on my messaging bot

### ISSUE THREAD

**Issue by suhashr** [line/line-platform-feedback#39]
I currently have a developer trial version on my messaging bot but I would like to have a paid plan so that I can add a premium id to my bot. But every time I click on the price plan I get this:
![image](https://user-images.githubusercontent.com/16915440/34202559-a1be94c8-e5aa-11e7-8072-eb59562837c1.png)
Is there anything I'm missing here?

**Comment by benjaminfauchald** [comment]
We are using an offical  LINE@ account, but the option to enable the API is not there.

So we are missing this option below:
![29768308-b9fa3490-8c20-11e7-8e02-b2a93035e1ea](https://user-images.githubusercontent.com/8008370/34250111-6c6470c6-e66e-11e7-9b6d-3ba7876c1edb.png)

It says that verified accounts is only available in certain regions where Thailand (where we are located) in one of the regions that are supported.

![screenshot 2017-12-21 16 39 05_preview](https://user-images.githubusercontent.com/8008370/34250167-9038ccae-e66e-11e7-893f-a298c360d181.png)

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
