### ISSUE TITLE
Availability of Messaging API and Line login in Thailand?

### ISSUE THREAD

**Issue by ZenDevMaster** [line/line-platform-feedback#42]
We have a premium Line ID in the Thailand market and we're anxious to integrate the Messaging API to our Zendesk for managing customer support issues in one place, the same as we already do for all of our other customer support channels. 

We'd also like to develop a bot that will reply to customer inquiries about the status of their orders with us and offer some automated replies. 

It seems like the Messaging API is currently only available on a developer account and cannot be turned on for our premium line ID.  

Is there any info about when this will be available in Thailand?  Do we need to become a LINE Partner, or if there is some other way we can obtain access to the API another way?

**Comment by iknowterry** [comment]
Hello @ZenDevMaster,
Thank you for reaching out to us and for your effort integrating LINE as one of your Zendesk channel. In Thailand, Messaging API is still only available for public access through developer account. As for real account usage with Premium ID, the option is available for discussion as LINE Partner. I would suggest to have separate discussion regarding this topic.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
