### ISSUE TITLE
LINE SDK for iOS sends users without LINE to Safari

### ISSUE THREAD

**Issue by yrmts** [line/line-platform-feedback#45]
According to Apple, apps that use the LINE SDK for iOS for registration/login violates the following guideline:

> 4.2.3 Your app should work on its own without requiring installation of another app to function.

Our app was recently declined for the above reason.

![2017-12-29 16 47 37](https://user-images.githubusercontent.com/6986122/34432135-1b29415a-ecb8-11e7-87e5-8c9a8175a19b.png)

The contained screenshot:
![attachment-4000056934146082591screenshot-1217-150221 1](https://user-images.githubusercontent.com/6986122/34432140-2502159e-ecb8-11e7-87b5-1844d2c573a1.png)

Please revise the LINE SDK to match the following suggestion by Apple:

> We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

**Comment by mrmaakun** [comment]
Hi @yrmts 

We have updated the SDK so that it performs the web login process in a Safari View Controller.

https://developers.line.me/en/news/#line-sdk-for-ios-4-1-0-released-2018-01-29

Please give this SDK a try.

**Comment by LintonJi** [comment]
I tried to use the 'LineSDKLogin.sharedInstance().startWebLogin()', but did not respond after clicking agree, what should I do?

**Comment by LintonJi** [comment]
Hi @mrmaakun 
I tried to use the 'LineSDKLogin.sharedInstance().startWebLogin()', but did not respond after clicking agree, what should I do?

**Comment by mrmaakun** [comment]
Hi @LintonJi

Do you see any logs coming from the SDK when you press the agree button?

It would also be helpful if you could check to make sure the iOS SDK settings on your channel are set properly (especially the URL scheme):

https://developers.line.me/en/docs/line-login/ios/integrate-line-login/#configuring-your-channel

**Comment by LintonJi** [comment]
Hi @mrmaakun

**Comment by LintonJi** [comment]
Hi @mrmaakun Thanks for your reply, I found the reason is that the name in the URL scheme is uppercase.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
