### ISSUE TITLE
'NSInvalidArgumentException', reason: '+[NSString LineSDK_queryStringWithDictionary:]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by foocarolyn** [line/line-platform-feedback#47]
Hi,

I have downloaded the framework and linked it in my project instead of using the pod to install it and encountered this error while I was trying to initiate the login process.

Below is the stack trace:

```2018-01-03 00:04:13.161092+0800 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSString LineSDK_queryStringWithDictionary:]: unrecognized selector sent to class 0x1b2f87a20'
*** First throw call stack:
(0x182cc7d38 0x1821dc528 0x182cd5138 0x182ccd6e4 0x182bb30dc 0x1022415b4 0x10224a578 0x102249f90 0x102247688 0x1022478b8 0x10223ff04 0x10223fa2c 0x10223f918 0x1020c9b40 0x1020ca424 0x1020ca24c 0x10212c790 0x1021418a0 0x1020a764c 0x1020a7538 0x1020c8bc4 0x10208c0d4 0x19911db84 0x18c08f300 0x18c08a7d0 0x18c05bde8 0x18c97eca0 0x18c981110 0x18c97a27c 0x182c70358 0x182c702d8 0x182c6fb60 0x182c6d738 0x182b8e2d8 0x184a13f84 0x18c0bf5e0 0x1020c94d8 0x1826b256c)```

**Comment by lianleven** [comment]
same error

**Comment by Sally-007** [comment]
I'm confused about it. Hope to get the answer

**Comment by DwightDing** [comment]
I download the latest version of the SDK， same error

**Comment by harady** [comment]
same error

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
