### ISSUE TITLE
Image/Image Carousel Messaging API semantics

### ISSUE THREAD

**Issue by kitagawa72** [line/line-platform-feedback#52]
Line Image /Image Carousel Messaging API are working well in general.
However, I met following undocumented problems with these API

1.  Sending image with same previewURL/URL frequently by Image API,  suddenly they were not able to
be presented.
2.  Sending image by image Carousel with same ImageUrl in JSON frequently within short period,
it was not to be presented suddenly. 

Are there any restriction with image URL handling that are undocumented.  

I look forward to hearing from other developers or Line engineers.

Thank you.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
