### ISSUE TITLE
RichMenu API Usage

### ISSUE THREAD

**Issue by kazuki-ma** [line/line-platform-feedback#57]
Migrated from https://github.com/line/line-bot-sdk-java/issues/171

> From https://github.com/ralphlai
>
> Hi,Is it possible that creating a richmenu and display to every user by default?
> What I mean is like LINE Manager platform (https://admin-official.line.me), creating a rich menu and set "Display". Every user can see it immediately. Seems that I must have to link menu to user first.
> 
> Another question, I do not see any update api of rich menu. Is it possible to update rich menu after creating?

**Comment by kazuki-ma** [comment]
> Hi,Is it possible that creating a richmenu and display to every user by default?

No. You can create default rich menu only by LINE Manager platform (https://admin-official.line.me).

>  Is it possible to update rich menu after creating?

Sorry also no. you need create new rich menu when you want to show another contents.

**Comment by leo5j472421** [comment]
So  rich menu image can't be updated to replace the old one?

**Comment by synk** [comment]
@leo5j472421 You cannot change rich menu image.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
