### ISSUE TITLE
Add mentions to Message object

### ISSUE THREAD

**Issue by Nilpo** [line/line-platform-feedback#66]
Can you add a new property to the Text Message object that includes a list of userIds that were @mentions in the message? Since display names can contain spaces, parsing them is extremely difficult and it very taxing to fetch all members of a group and then fetch each profile individually to compare display names to the message text.

**Comment by Nilpo** [comment]
Does anyone read these? I'd love to get this added as a Feature Request.

**Comment by synk** [comment]
It's in our backlog. but there's been no progress on that.

**Comment by Nilpo** [comment]
Thank you. I appreciate the update.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
