### ISSUE TITLE
Cannot upload richmenu image at LINE@Manager

### ISSUE THREAD

**Issue by morugu** [line/line-platform-feedback#69]
I tried to upload richmenu sample image ( https://scdn.line-apps.com/n/line_official_v2/img/MdFRM/type_richmenu_guide/2500x1686/02.png ) at LINE@Manager.

however system return error "admin-official.line.me Says 一時的なエラーにより、リクエストが完了しませんでした。もう一度お試しください。".

**Comment by kenakamu** [comment]
It works for me by using the image you provided. Do you still have the issue?

**Comment by morugu** [comment]
yes.

<img width="870" alt="screen shot 2018-02-21 at 10 51 44" src="https://user-images.githubusercontent.com/1635118/36459068-6548fe3a-16f5-11e8-8d41-ef76d638f4cc.png">

**Comment by kenakamu** [comment]
I tried in Japanese settings as well but it just worked. So this maybe only your channel or account :(
Do you have another channel to test it out for troubleshooting so that LINE forks can help you better?

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
