### ISSUE TITLE
Can not change the rich menu in the background with Android's LINE

### ISSUE THREAD

**Issue by ta-sakai** [line/line-platform-feedback#70]
When displaying the internal browser of LINE and changing the rich menu (* 1) while the talk screen is in the background
Even when closing the browser and transitioning to the talk screen, the menu has not been changed.
If you close the talk screen and display it again, the menu will be changed.

In the iPhone LINE application, if you do the same operation, the rich menu will be changed instantly.

** 1 It changed with the following API
`POST https://api.line.me/v2/bot/user/{userId}/richmenu/{richMenuId}`

**Comment by YichingChiang** [comment]
Hi, @ta-sakai 
We appreciate your reporting this issue to us. Our team is working on it. We will update you when it is done.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
