### ISSUE TITLE
Improvement on Rich Menu tutorial

### ISSUE THREAD

**Issue by chaintng** [line/line-platform-feedback#73]
I'm trying to follow this tutorial
https://developers.line.me/en/docs/messaging-api/using-rich-menus/

1) Firstly, the image size in the tutorial is not match what LINE is expecting.
Anyway, i resize it to proper size and continue the tutorial

2) Seconday, at the very last step to link rich menu to user id
I got `HTTP/1.1 411 Length Required`
and 
```
<HTML><HEAD>
<TITLE>Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
Reference&#32;&#35;7&#46;5267f648&#46;1519313978&#46;176a7762
</BODY>
</HTML>
```

when call
```
curl -v -X POST https://api.line.me/v2/bot/user/{USER_ID}/richmenu/{RICH_MENU_ID} \
-H "Authorization: Bearer {CHANNEL_ACCESS_TOKEN}"
```

So, I need to add `-d ''`
to getting `200` return

I can help contribute the document if you link me to repo.

Thanks

**Comment by KosukeKamiya** [comment]
Hi @chaintng ,
For #1, it's our mistake so we'll fix it soon. Thank you for your feedback.

For #2, we can't reproduce this error. The attached screenshot is the log that we use this API as documentation shown. Could you please check your request is same as our testing?
![image](https://user-images.githubusercontent.com/16027545/38854741-6e9a5668-425c-11e8-988f-f2fb8f9edaff.png)

**Comment by sreeramcapillary** [comment]
Any update on this..??? We are still facing this issue.

**Comment by chaintng** [comment]
![image](https://user-images.githubusercontent.com/2979072/41295248-49922cf2-6e84-11e8-96ba-ff5ffbc98804.png)

@KosukeKamiya look like the problem is only in MacOSX
Can you please confirm?

**Comment by sreeramcapillary** [comment]
@chaintng Hi, Yesterday i tried this in Mac and it worked fine after adding -d ''.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
