### ISSUE TITLE
User language / localisation API?

### ISSUE THREAD

**Issue by gfmio** [line/line-platform-feedback#74]
Hi!

I asked at [https://github.com/line/line-bot-sdk-nodejs/issues/58](https://github.com/line/line-bot-sdk-nodejs/issues/58) if there is any way to get a user's preferred language / localisation from the API? I've been told no, but to also post this here as feedback / a potential feature request.

Right now, I'm trying to implement it as some kind of dialogue, but it's a bit of a clumsy solution. For this project, I only need to support two languages, which is doable, but if you had to work with let's say 7, 13 or even 30, it becomes unmanageable. Hence, it would be cool to add that to the API.

Thanks,
@gfmio

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
