### ISSUE TITLE
AWS Lambda doesn't work with message API

### ISSUE THREAD

**Issue by kingofwhales** [line/line-platform-feedback#81]
### Issues
When sending requests to Line Message API to reply/push messages, it never gets a response back: neither success nor error response.

However, the code works locally or with Postman, I was able to push messages to the user. But when deployed on AWS Lambda, it never gets a response back.  I am suspecting that this has something to do with the CA provider.

If the user sends another message, at this point this error shows up in the log: 

`2018-03-07T03:38:14.053Z	f5c1d4d4-21b8-11e8-bf26-9f336d65236e	{ Error: socket hang up
at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
at TLSSocket.g (events.js:292:16)
at emitNone (events.js:91:20)
at TLSSocket.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9)
code: 'ECONNRESET',
config: `

### Possible Causes
When checking the CA provider for my [lambda hosting](https://gpbtblzetc.execute-api.us-east-1.amazonaws.com/dev),  I found this:  **Amazon Root CA 1**

That is actually not in the[ Official CA list](https://developers.line.me/media/messaging-api/build-bot/ca_root_v2.txt). Could this be the reasons?  Lambda is really popular now so maybe should add Amazon Root CA 1 to the list too?

Currently testing on other service provider. Will update with the results soon.

**Update**: 2018.03.07
1. The exact same code works when I hosted it on [Heroku,](https://powerful-ridge-93685.herokuapp.com/). It has _DigiCert High Assurance EV Root CA_ as its' provider.  

### Reproduction Link
https://github.com/kingofwhales/lambda_line_bot_test

### Steps to Reproduce
1. Clone the repo and Install the Dependency
2. Configure your own AWS credentials: https://serverless.com/framework/docs/providers/aws/guide/credentials/
3. Deploy the repo
`sls deploy`
4. Add this line bot as friend: https://qr-official.line.me/M/V01p5--SxA.png  Send a message
5. Check your Lambda Server Logs. 
6. No response back from the Line bot server, neither success or error
7. Try this locally or in Postman. Successfully push messages to users.
`sls offline --port 8080`

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
