### ISSUE TITLE
image_aspect_ratio and default_action

### ISSUE THREAD

**Issue by khanwhlee** [line/line-platform-feedback#83]
I have looked it up from open and close issues, don't really find any similar issues...

I tried to use new functions today on my carousel templates.
In order to enlarge photo display, I set image_aspect_ratio="square", it turns out nothing is changed, image_size included.
Besides, I tried the default_action on every carousels, and no response as well.

Not sure it's carousel problem or developer trial...

**Comment by synk** [comment]
I've tried it with cURL and JSON. It works well. Which SDK do you use?

**Comment by khanwhlee** [comment]
python line-bot-sdk
I was thinking the same thing
Might use url first before figure out what went wrong in python.
Tried button template and failed, too.

**Comment by khanwhlee** [comment]
so...

I read source code from my site package.
I used pip install line-bot-sdk 3 days ago, but somehow the source code is different from source code on github.

So I edit the source code in my site package and got it work!
Thanks. synk!

BTW smarter way might be clone the depository directly...
https://github.com/line/line-bot-sdk-python

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
