### ISSUE TITLE
An error occurred when sending the webhook.

### ISSUE THREAD

**Issue by porphyr** [line/line-platform-feedback#84]
When I try to verify my Line bot webhook I get the error message
"An error occurred when sending the webhook."

The Webhook URL is
https://markreiche.de/webhook

From the server logs I can see that no request is sent to the site.
The Site certificate is valid (can be opened in the browser), and the Root CA (CN = DST Root CA X3) is in the list of accepted CA's (https://developers.line.me/media/messaging-api/build-bot/ca_root_v2.txt)

**Comment by kazuki-ma** [comment]
@porphyr Is the url you provided `https://markreiche.de/webhook`  right?
I got `Not Found The requested URL /webhook was not found on this server.` from Apache server when I opens URL.

**Comment by jasonlcs** [comment]
> var privateKey  = fs.readFileSync('sslcert/private.key', 'utf8');
> var certificate = fs.readFileSync('sslcert/certificate.crt', 'utf8');
> var credentials = {key: privateKey, cert: certificate};

//failed ==> got no request and show "An error occurred when sending the webhook."

> var privateKey  = fs.readFileSync('sslcert/private.key', 'utf8');
> var certificate = fs.readFileSync('sslcert/certificate.crt', 'utf8');
> var cafile =      fs.readFileSync('sslcert/ca_bundle.crt','utf-8');
> var credentials = {ca:cafile, key: privateKey, cert: certificate};

//failed ==> got no request and show "An error occurred when sending the webhook."

> var privateKey  = fs.readFileSync('sslcert/private.pem', 'utf8');
> var certificate = fs.readFileSync('sslcert/certificate.pem', 'utf8');
> var cafile =      fs.readFileSync('sslcert/ca_bundle.pem','utf-8');
> var credentials = {ca:cafile, key: privateKey, cert: certificate};

> var app = express();
> 
> var linebotParser = bot.parser();
> app.post('/', linebotParser);
> var server = https.createServer(credentials, app).listen(8080, function() {
> ...
> }

//and this one is OK

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
