### ISSUE TITLE
Enabling Messaging API on Channel Created by Another User

### ISSUE THREAD

**Issue by pbills** [line/line-platform-feedback#89]
I work for Mobile Coach, a bot authoring platform company based in the US. We use the LINE messaging API on several channels all through the same provider that we created. We have a client in Thailand who created his own channel and added me as an admin to it, but I do not see any option anywhere to enable messaging API on his channel.

We have also tried adding the client as an admin for our provider in LINE developers, but none of his created channels appear in our channel list after adding him.

Is there a way to enable messaging API for his channel that we are not seeing? Or is there a way to transfer ownership of a channel so that we can have the same permissions that we have on our own channels?

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
