### ISSUE TITLE
Connect Line@ with Line Messaging API

### ISSUE THREAD

**Issue by punapun1** [line/line-platform-feedback#91]
Hi Line Team,

I have a Line@ Account that I want to link a Messaging API bot to, I was wondering if it will be possible to connect them, and the bot running & replying when a person messages the Line@ account. Please help guide through the steps needed to have this running. Our messaging API is working, but I'm unable to link it to Line@ account.

**Comment by kazuki-ma** [comment]
You can't link existing messaging channel with existing LINE@ account.
Instead, you can enabling messaging api on the LINE@ account.

Please open https://admin-official.line.me/ and open
 `Account configuration > Messaging API Configuration`

**Comment by katopz** [comment]
@kazuki-ma I can't find any menu related to `Account configuration > Messaging API Configuration`?
![image](https://user-images.githubusercontent.com/97060/44045912-37877d90-9f54-11e8-93ba-5bfb9b4b7e9d.png)

Thanks

**Comment by ppetpadriew** [comment]
I can't find that too. Seems like it does not support ?

![image](https://user-images.githubusercontent.com/6456783/49688622-91132180-fb47-11e8-963b-1af3a99d12d4.png)

![image](https://user-images.githubusercontent.com/6456783/49688731-df74f000-fb48-11e8-812f-c18da9089d14.png)

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
