### ISSUE TITLE
What's the ratio of clients support LIFF?

### ISSUE THREAD

**Issue by IguteChung** [line/line-platform-feedback#96]
The support spec of LIFF:

iOS: iOS 8 or later. iOS 9 or later uses WKWebView and iOS 8.x uses UIWebView.
Android: 4.2 (Jelly Bean MR1 and API level 17) or later
LINE app: Version 7.14 or later

I wonder what is the official number of ratio which support LIFF?

**Comment by tori3** [comment]
Hi @IguteChung.

Does it mean the ratio of the user environment using LIFF?

Please refer to information published by Google and Apple regarding OS.

https://developer.android.com/about/dashboards/
https://developer.apple.com/support/app-store/

I can not tell you detailed number about LINE version.
Since v7.14 is a version about one year ago, it can be said that almost LINE users are in an environment where LIFF can be used.
